# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: GitHub Pages deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
      - name: Use Node.js 20.14
        uses: actions/setup-node@v1
        with:
          node-version: '20.14.0'
          
      - name: Show version
        run: node -v && npm -v
      - name: Set env
        run: export NODE_OPTIONS=--openssl-legacy-provider
        
      - name: Installing my packages
        run: rm -rf node_modules && rm -rf package-lock.json && rm -rf yarn.lock && yarn cache clean && yarn install

      - name: Build my App
        run: npm run build && npm run export && touch ./out/.nojekyll

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: public # The branch the action will deploy to
          FOLDER: out # The folder the action will deploy to
